name: debuggable_http_client
description: Wrapper around http.Client that adds beforeRequest() property.
version: 0.1.0
repository: https://github.com/martinsellergren/debuggable_http_client

environment:
  sdk: ">=2.18.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  http: ^1.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
